### ISSUE TITLE
Documentation of Cooklang.l

### ISSUE THREAD

**Issue by Net-Mist** [cooklang/cook-in-c#12]
Hello !
I'm trying to understand the content of the file `Cooklang.l`. From my understanding, the punctuation, symbolic and alpha characters are encoded in a very generic way to support several encoding. Am I right ? How was the list of encoding generated ?

also it seems the command `flex -Ca Cooklang.l` takes a very long time to run. (run for more than 2 hours and didn't finished yet on my computer). Is there a way to speed-up this command ?

**Comment by Seth-Harlaar** [comment]
The punctuation, symbolic, and alphabetical characters are encoded in utf-8. I generated the list using the docs from the Unicode Character Database and some python. The script I used is in one of my repositories, here: https://github.com/Seth-Harlaar/flexer-unicode-regular-expressions. 
Yes, unfortunately because of the amount of code points being used that command does take a very long time. That is why I generally use the binary_clean make command so as to avoid removing the lex.yy.c file and having to do it over again. 
I have looked into ways of speeding it up and have not had any luck, besides getting a faster computer. For comparison it runs in about 1 hour and 50 minutes on my computer. There is slight room for optimization in the code point generation using hex ranges instead of individual values, but I did not think it would provide any reasonable increase in execution time, given the way that Unicode code points are organized.
